name: release_model

env:
  model_name: "replicate/llama-7b"

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: [self-hosted, gpu-a100]
    strategy: 
      matrix:
        model: ['llama-7b']
    steps:
      - uses: actions/checkout@v3

      - name: Install Cog
        run: |
          sudo curl -o /usr/local/bin/cog -L https://github.com/replicate/cog/releases/latest/download/cog_`uname -s`_`uname -m`
          sudo chmod +x /usr/local/bin/cog
      
      - name: Select model
        run: 
          cog run python select_model.py --model_name ${{ matrix.model }} --model_path ${{ secrets.LLAMA_7B_PATH }}
  
      - name: Log in to Replicate
        env:
          REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
        run: |
          echo $REPLICATE_API_TOKEN | cog login --token-stdin

      - name: Push to Replicate
        run: |
          cog push r8.im/${{ env.model_name }}
